<div class="recommend-item">
    <div class="recommend-item-top-container">
        <div class="recommend-item-image">
            <img src="<?php echo $imgsrc; ?>">
        </div>
        <div class="recommend-description">
            <div class="recommend-item-title">
                <a href="/book/<?php echo $id ?>">
                    <?php echo $name ?>
                </a>
            </div>
            <div class="recommend-item-rating">
                <?php echo $author ?> - <?php echo $rating; ?> / 5.0 (<?php echo $vote ?> Vote)
            </div>
            <div class="recommend-item-desc">
                <?php echo $description ?>
            </div>
        </div>
    </div>
  <!--
  <div class="result-item-button">
    <a href="/book/<?php //echo $id ?>">
      <button class="button">Detail</button>
    </a>
  </div>
  -->
</div>